Logic/Logic/HilbertStyle2.lean, Logic/Logic/LogicSymbol.lean, Logic/Modal/Normal.lean, Logic/Modal/Normal/Axioms.lean, Logic/Modal/Normal/Completeness.lean, Logic/Modal/Normal/Formula.lean, Logic/Modal/Normal/HilbertStyle.lean, Logic/Modal/Normal/LogicSymbol.lean, Logic/Modal/Normal/ModalCube.lean, Logic/Modal/Normal/Semantics.lean, Logic/Modal/Normal/Soundness.lean, Logic/Propositional/Basic/Completeness.lean, README.md
=> Strong Completeness of Normal Modal Logic

Logic/Modal/LogicSymbol.lean, Logic/Modal/Normal.lean, Logic/Modal/Normal/Axioms.lean, Logic/Modal/Normal/Completeness.lean, Logic/Modal/Normal/Deduction.lean, Logic/Modal/Normal/Formula.lean, Logic/Modal/Normal/Geach.lean, Logic/Modal/Normal/HilbertStyle.lean, Logic/Modal/Normal/LogicSymbol.lean, Logic/Modal/Normal/Semantics.lean
例えば今後，1-arityの様相演算子を1つだけ持つ論理(Lax Logic?など)や2個より多く持つ論理(Bimodal logic)などを考えることに備えて（現状予定は無いが）言語を拡張出来るようにした．
これに伴って今まで`ModalLogicSymbol`は`StandardModalLogicalConnective`と命名した．Standardという命名が一般的かどうかはわからない．
=> refactor(Modal): Refactor Modal Logical Connectives

.github/workflows/ci.yml, .github/workflows/docs.yml
遅すぎるのでドキュメントの生成はdoc-gen4を信頼して`master`でのみで行うこととし，また`/docs`以下にデプロイすることにする．
=> ci: Deploying docs to `/docs`

Logic/Modal/Standard/Deduction.lean, Logic/Modal/Standard/Formula.lean, Logic/Modal/Standard/Geach.lean, Logic/Modal/Standard/HilbertStyle.lean, Logic/Modal/Standard/Kripke/Geach/Completeness.lean, Logic/Modal/Standard/Kripke/Soundness.lean, Logic/Modal/Standard/System.lean, md/src/standard_modal/GL.md
様相論理の演繹体系に推論規則を増やして拡張するテストとして，次の事実を証明した．
Henkin公理`𝐇`，Löb規則`(𝐋)`，Henkin規則`(𝐇)`を導入する．
```
protected abbrev H := □(□p ⟷ p) ⟶ □p
class LoebRule where
loeb {p : F} : 𝓢 ⊢ □p ⟶ p → 𝓢 ⊢ p
class HenkinRule where
henkin {p : F} : 𝓢 ⊢ □p ⟷ p → 𝓢 ⊢ p
```
このとき`𝐆𝐋 =ₛ 𝐊𝟒(𝐋) =ₛ 𝐊𝟒(𝐇) =ₛ 𝐊𝟒𝐇`．
なお，`𝐊𝐇`はKripke完全ではない（らしい）．
=> feat(Modal): Logics equivalent to `𝐆𝐋`

Logic/Logic/HilbertStyle/Basic.lean, Logic/Logic/HilbertStyle/Context.lean, Logic/Logic/HilbertStyle/Supplemental.lean, Logic/Logic/LogicSymbol.lean, Logic/Modal/Standard/Formula.lean, Logic/Modal/Standard/HilbertStyle.lean, Logic/Modal/Standard/Kripke/Completeness.lean, Logic/Modal/Standard/Kripke/ModalCompanion.lean, Logic/Propositional/Superintuitionistic/Formula.lean, Logic/Propositional/Superintuitionistic/Kripke/Classical.lean, Logic/Propositional/Superintuitionistic/Kripke/Semantics.lean
#69 に関連して，このプロジェクトで採用している1階述語論理の体系において`~p = (p ⟶ ⊥)`が成り立っているのか不明だった（おそらく違う？）ので，Supplementalの演繹を`𝓢`上で否定の同値性が言えれば良いという仮定に弱めた．　
```lean
protected class NegationEquiv (𝓢 : S) where
neg_equiv {p} : 𝓢 ⊢ ~p ⟷ (p ⟶ ⊥)
```
=> feat: Negation equivalence on System

.github/workflows/ci.yml
GitHubのキャッシュ仕様を考えるとPR駆動のとき`master`以外の別ブランチのキャッシュを取りに行くことは無いためこの識別は不要．また`master`とバージョンが違う場合はそのキャッシュを利用しないためこれでよいはず
=> ci: Fix cache key

Logic/FirstOrder/Incompleteness/DerivabilityCondition.lean, Logic/Logic/HilbertStyle/Basic.lean, Logic/Logic/HilbertStyle/Context.lean, Logic/Logic/HilbertStyle/Supplemental.lean, Logic/Modal/Standard/Boxdot.lean, Logic/Modal/Standard/ConsistentTheory.lean, Logic/Modal/Standard/Deduction.lean, Logic/Modal/Standard/Formula.lean, Logic/Modal/Standard/Kripke/Completeness.lean, Logic/Modal/Standard/Kripke/Filteration.lean, Logic/Modal/Standard/Kripke/Geach.lean, Logic/Modal/Standard/Kripke/ModalCompanion.lean, Logic/Modal/Standard/Kripke/Preservation.lean, Logic/Modal/Standard/Kripke/Semantics.lean, Logic/Modal/Standard/Maximal.lean, Logic/Modal/Standard/PLoN/Semantics.lean, Logic/Modal/Standard/Provability/Basic.lean, Logic/Modal/Standard/System.lean, Logic/Propositional/Superintuitionistic/Deduction.lean, Logic/Propositional/Superintuitionistic/Formula.lean, Logic/Propositional/Superintuitionistic/Kripke/Classical.lean, Logic/Propositional/Superintuitionistic/Kripke/Completeness.lean, Logic/Propositional/Superintuitionistic/Kripke/Semantics.lean, Logic/Propositional/Superintuitionistic/Kripke/Soundness.lean, Logic/Propositional/Translation.lean
`~p`を`p ⟶ ⊥`の略記として導入すると次のような定義を用いるときmatchなどが微妙に使えないため困る．
```lean
def complement : Formula α → Formula α
| ~p => p
| _ => ~p
```
そのためプリミティヴな記号として導入したい．
直観主義様相論理のようなものも考えるとしたら`◇`も略記として導入するのは止めて証明体系上同値および意味論上同値で定義し直したほうが良いかもしれない．
=> fix(Modal): Remove Negation Abbreviation

Logic/FirstOrder/Incompleteness/DerivabilityCondition.lean, Logic/Logic/HilbertStyle/Basic.lean, Logic/Logic/HilbertStyle/Context.lean, Logic/Logic/HilbertStyle/Supplemental.lean, Logic/Logic/LogicSymbol.lean, Logic/Modal/Standard/ConsistentTheory.lean, Logic/Modal/Standard/Kripke/Completeness.lean, Logic/Modal/Standard/Kripke/Geach.lean, Logic/Modal/Standard/Kripke/ModalCompanion.lean, Logic/Modal/Standard/PLoN/Completeness.lean, Logic/Modal/Standard/System.lean, Logic/Propositional/Superintuitionistic/Kripke/Completeness.lean
- 証明の見通しが悪すぎるため`List.conj₂`, `List.disj₂`に対し`⋀`と`⋁`の記号を導入
- Hilbert流で`conj`, `disj`と言ったときは普通明らかに`conj₂`, `disj₂`のことを指すので`₂`は省略する．
- Modal以下の`Theory.Consistent`を`T *⊬[Λ]! ⊥`の単なる略記として書き換え．
=> refactor: List Conjunction and Disjunction

Logic/Modal/Standard/Kripke/Completeness.lean, Logic/Modal/Standard/Kripke/Dot3.lean, Logic/Modal/Standard/Kripke/Geach.lean, Logic/Modal/Standard/Kripke/Ver.lean
Kripke意味論のカノニカルモデルのパラメータを公理集合にしていたが面倒なので普通に`Λ`で与えるようにした．`𝐆𝐋`の完全性をこれでやってみて支障が無さそうならマージする．
=> refactor: Change parameter of Kripke canonical model

Logic/Logic/System.lean, Logic/Modal/Standard/Deduction.lean, Logic/Modal/Standard/Geach.lean, Logic/Modal/Standard/Kripke/Geach.lean, Logic/Modal/Standard/Kripke/Reducible.lean, Logic/Modal/Standard/Kripke/Soundness.lean
様相論理の`StrictlyWeakerThan`を示すには一つ一つフレームを構成するしかなさそう（一般化された方法はない）ということがわかったのでそれに関しての修正．フレームの構成としては例えば下記のgeneratorを使えば出してくれる．
https://www.umsu.de/trees/#p~5~8~9p
ただしそれを踏まえても $\bf K,T,B,D,4,5$ で残り10個ほどある．
=> fix(Modal): Fix StrictlyWeakerThan relations

Logic/Logic/HilbertStyle/Supplemental.lean, Logic/Modal/Standard/Boxdot.lean, Logic/Modal/Standard/System.lean
`𝐆𝐋`は`𝐆𝐫𝐳`を介してboxdot変換で埋め込める．逆を証明するには意味論的な分析がいる（はず）
```lean
lemma boxdotTranslatedGL_of_Grz : 𝐆𝐫𝐳 ⊢! p → 𝐆𝐋 ⊢! pᵇ
```
=> feat(Modal): Boxdot Translation between `𝐆𝐋` and `𝐆𝐫𝐳` Part.1

Logic/Logic/Axioms.lean, Logic/Logic/HilbertStyle/Basic.lean, Logic/Logic/HilbertStyle/Context.lean, Logic/Logic/HilbertStyle/Lukasiewicz.lean, Logic/Modal/Standard/Deduction.lean
#124 で様相論理の記号を`⟶`と`⊥`だけに制限することにした（すなわち古典的なものだけを考えることにした）ため，演繹体系もそれに伴って命題論理の部分はŁukasiewiczの3公理体系で十分なように削除した．
演繹体系が「`⟶`と`⊥`から他の論理記号が略記として定義可能かつŁukasiewiczの3公理を持っている」ことに対応するclass`System.Lukasiewicz`を定め，これを満たしている場合`System.Classical`になる．
ただしこれは`andInst`や`dne`などが証明可能なことを`System.Lukasiewicz`だけでやる必要があり（おそらく演繹定理も微妙に使えないかもしれない）難解なパズルで面倒，なにかよい文献があれば教えてほしい．一応[lean-logic](https://github.com/iehality/lean-logic/blob/main/src/provability.lean)なども参考にしてみているが．
=> feat: Łukasiewicz's  3-Axioms System

Foundation/IntProp/ConsistentTableau.lean, Foundation/Logic/HilbertStyle/Basic.lean, Foundation/Logic/HilbertStyle/Context.lean, Foundation/Logic/HilbertStyle/Lukasiewicz.lean, Foundation/Logic/HilbertStyle/Supplemental.lean, Foundation/Logic/LindenbaumAlgebra.lean, Foundation/Modal/Boxdot/Basic.lean, Foundation/Modal/Complemental.lean, Foundation/Modal/ConsistentTheory.lean, Foundation/Modal/Formula.lean, Foundation/Modal/Geach.lean, Foundation/Modal/Hilbert.lean, Foundation/Modal/Kripke/Completeness.lean, Foundation/Modal/Kripke/Dot3.lean, Foundation/Modal/Kripke/Filteration.lean, Foundation/Modal/Kripke/GL/Completeness.lean, Foundation/Modal/Kripke/GL/Tree.lean, Foundation/Modal/Kripke/Semantics.lean, Foundation/Modal/LogicSymbol.lean, Foundation/Modal/Maximal.lean, Foundation/Modal/ModalCompanion/Basic.lean, Foundation/Modal/System.lean, lakefile.lean
`Supplemtanl.lean`および`Modal/System.lean`のクラス系を全部書き換えるのは現実的ではない/あまりにもコードが長くなりすぎるという気がして
```
set_option deprecated.oldSectionVars true
```
などを使って一旦延期してしまっている．
=> Update to 4.13 for Modal

Foundation/Modal/Kripke/ExtendRoot.lean, Foundation/ProvabilityLogic/Grz/Completeness.lean
=> add(ProvabilityLogic): Strong Interpretation on Standard Model

Foundation/Modal/Kripke/Basic.lean, Foundation/Propositional/Kripke/Basic.lean
既存のコードの修正はしていないが，今後は使えるようにした．
Fixes #313
=> refactor(Modal/Kripke, Prop/Kripke): `CoeSort` on `Model.World`

Foundation/Logic/Entailment.lean
fix #415 
原因はわからないが依然として `trans _` は使えない．`calc` は使えるようになったはずなので，そちらを用いるといいと思う．
=> add(logic) : `WeakerThan` instances

Foundation/Modal/ModalCompanion/Cl.lean, Foundation/Modal/ModalCompanion/Int.lean, Foundation/Modal/ModalCompanion/KC.lean, Foundation/Modal/ModalCompanion/LC.lean, Foundation/Propositional/ClassicalSemantics/Hilbert.lean, Foundation/Propositional/Hilbert/Glivenko.lean, Foundation/Propositional/Hilbert/WellKnown.lean, Foundation/Propositional/Kripke/Logic/Cl.lean, Foundation/Propositional/Kripke/Logic/Int.lean, Foundation/Propositional/Kripke/Logic/KC.lean, Foundation/Propositional/Kripke/Logic/KP.lean, Foundation/Propositional/Kripke/Logic/LC.lean, Foundation/Propositional/Logic/Letterless_Int_Cl.lean, Foundation/Propositional/Logic/PostComplete.lean, Kite/Propositional.lean, Kite/propositional.typ
そもそも`Logic.Int`として定義しなくとも良いような気がした．
```lean
notation "𝐈𝐧𝐭" => Hilbert.Int.logic
```
様相論理で`𝐊𝐏`が被るが，型から上手く推論されるような気もする．ダメだったら置き換えればよいだけなのでとりあえずこれで試す．
close #422
=> refactor(Prop): Use notation for Logics

Foundation/Meta/ClProver.lean, Foundation/Meta/Test.lean
`𝓣 ⪯ 𝓢` が示された Entailment についての証明 `𝓣 ⊢! ...` も仮定に使用できるようにした．
```lean
variable {S F : Type*} [DecidableEq F] [BasicModalLogicalConnective F] [Entailment F S]
variable {𝓢 𝓣 𝓤 : S} [𝓣 ⪯ 𝓢] [𝓤 ⪯ 𝓢] [Modal.Entailment.K 𝓢] {φ ψ ξ χ : F}
example (h₁ : 𝓣 ⊢! □φ ⭤ φ) (h₂ : 𝓤 ⊢! □ψ ⭤ ψ) : 𝓢 ⊢! φ ⋎ □ψ ⭤ □φ ⋏ φ ⋎ ψ := by cl_prover [h₁, h₂]
```
=> add(Meta): `cl_prover [...]` for hypotheses of weak entailment

Foundation/Modal/Entailment/Basic.lean, Foundation/Modal/Hilbert/Minimal/Basic.lean, Foundation/Modal/Neighborhood/AxiomC.lean, Foundation/Modal/Neighborhood/AxiomGeach.lean, Foundation/Modal/Neighborhood/AxiomM.lean, Foundation/Modal/Neighborhood/AxiomN.lean, Foundation/Modal/Neighborhood/Basic.lean, Foundation/Modal/Neighborhood/Completeness.lean, Foundation/Modal/Neighborhood/Logic/E.lean, Foundation/Modal/Neighborhood/Logic/E4.lean, Foundation/Modal/Neighborhood/Logic/EC.lean, Foundation/Modal/Neighborhood/Logic/EM.lean, Foundation/Modal/Neighborhood/Logic/EMC.lean, Foundation/Modal/Neighborhood/Logic/EMC4.lean, Foundation/Modal/Neighborhood/Logic/EMT.lean, Foundation/Modal/Neighborhood/Logic/EMT4.lean, Foundation/Modal/Neighborhood/Supplementation.lean
現在の実装で近傍フレームがカノニカルである `Frame.IsCanonical` ということを考えると素朴には下のようになる．
```
class Frame.IsCanonical (F : Frame) : Prop where
eq_world : F.World = MaximalConsistentSet 𝓢
box_proofset : ∀ φ, F.box (eq_world ▸ (proofset 𝓢 φ)) = eq_world ▸ (proofset 𝓢 (□φ))
```
しかしこの方法ではtruthlemmaを示すためには `Frame.IsCanonical.eq_world ▸ (∅ : Set (MaximalConsistentSet 𝓢)) = (∅ : Set F.World)` みたいな当たり前に成り立ってほしい集合に関しての演算に閉じなくなってしまう．
いま取っている方法は `(Set (MaximalConsistentSet 𝓢)) → (Set (MaximalConsistentSet 𝓢))` がカノニカルであるみたいな方針を取っているが，かなり微妙で教科書的な定義ではないし，「フレームがreflexiveである」という命題と「↑の関数がカノニカルである」といった性質の定義されるレベルがゴチャゴチャになってしまう．
=> add(Modal/Neighborhood): Supplementaion of Frame

Foundation/ProvabilityLogic/Classification/LetterlessTrace.lean, Foundation/ProvabilityLogic/SolovaySentences.lean
close #553
`SolovaySentences`をもとに戻し，それに伴って`LetterlessTrace`の証明を修正．おそらく大丈夫だと思うが一応レビューしてもらえると助かる．
=> fix(ProvabilityLogic): Remove `instFintypeWorldOfIsFiniteTree`
