FormalizedFormalLogic/Foundation

.editorconfig
.github/workflows/ci.yml
Logic.lean
Logic/Propositional/Basic/Formula.lean

- 最低限`lake build`が通ることをCI上で保証する
- 現状で`Logic/Propositional/Basic/Formula.lean`などが壊れているので修正

Add workflow to check build successfully

---

.github/workflows/ci.yml
.github/workflows/docs.yml

Fix caching on GitHub Actions

---

Logic/Logic/HilbertStyle2.lean
Logic/Modal/Normal.lean
Logic/Modal/Normal/Axioms.lean
Logic/Modal/Normal/Completeness.lean
Logic/Modal/Normal/Deduction.lean
Logic/Modal/Normal/Formula.lean
Logic/Modal/Normal/HilbertStyle.lean
Logic/Modal/Normal/LogicSymbol.lean
Logic/Modal/Normal/Semantics.lean
Logic/Modal/Normal/Soundness.lean

#16 #23 #24 でそれぞれ変更していた様相論理の記法の変更や補題の修正などをまとめ直した．
これによって #24  はマージ可能になる．

refactor(Normal Modal): Refactor lemmata and notations

---

Logic.lean
Logic/Logic/HilbertStyle2.lean
Logic/Propositional/Intuitionistic.lean
Logic/Propositional/Intuitionistic/Deduction.lean
Logic/Propositional/Intuitionistic/Formula.lean
Logic/Propositional/Intuitionistic/Kripke/Completeness.lean
Logic/Propositional/Intuitionistic/Kripke/LEM.lean
Logic/Propositional/Intuitionistic/Kripke/Semantics.lean
Logic/Propositional/Intuitionistic/Kripke/Soundness.lean
README.md

close #17 
現状のGentzen流の用意で上手く行くのかわからなかったので，とりあえず証明論はHilbert流で，意味論はKripkeモデルで形式化を行っている．

feat: Add Intuitionistic Propositional Logic

---

Logic/Propositional/Intuitionistic/Kripke/Completeness.lean
README.md

feat(IntProp): Disjunction Property

---

Logic/Modal/Normal.lean
Logic/Modal/Normal/Axioms.lean
Logic/Modal/Normal/Deduction.lean
Logic/Modal/Normal/HilbertStyle.lean
Logic/Modal/Normal/ModalCompanion.lean
Logic/Modal/Normal/ModalCube.lean
Logic/Modal/Normal/Semantics.lean
README.md

Add Gödel-McKensey-Tarski Theorem: `LO.Modal.Normal.companion_Int_S4`.
close #19

feat(IntProp, Modal): Gödel-McKinsey-Tarski Theorem

---

Logic/Modal/Normal/Axioms.lean
Logic/Modal/Normal/Completeness.lean
Logic/Modal/Normal/ModalCompanion.lean
Logic/Modal/Normal/ModalCube.lean
Logic/Modal/Normal/Semantics.lean

使いにくいため，様相論理の強弱を意味論ではなく証明論的な方法で再定義した．

refactor(Modal): Rewrite modal strongness

---

Logic/Modal/Normal/Irreflexive.lean

非反射的なフレームを定義する論理式の集合は存在しない
References: https://nishimura-yuki-website.glitch.me/article-irreflexivity-and-ml.html

feat(Modal): Undefinability of irreflexive

---

Logic/Modal/Normal.lean
Logic/Modal/Normal/Morphism.lean

`Morphism.lean`（旧`Irreflexive.lean`）をビルド対象に入れ忘れていたので修正

fix(Modal): Add `Morphism.lean` for build target

---

Logic/Logic/Deduction.lean
Logic/Logic/Init.lean
Logic/Logic/LogicSymbol.lean
Logic/Modal/Normal/Axioms.lean
Logic/Modal/Normal/Completeness.lean
Logic/Modal/Normal/Deduction.lean
Logic/Modal/Normal/Formula.lean
Logic/Modal/Normal/Geach.lean
Logic/Modal/Normal/HilbertStyle.lean
Logic/Modal/Normal/LogicSymbol.lean
Logic/Modal/Normal/ModalCompanion.lean
Logic/Modal/Normal/ModalCube.lean
Logic/Modal/Normal/Morphism.lean
Logic/Modal/Normal/Semantics.lean
Logic/Modal/Normal/Soundness.lean
Logic/Propositional/Intuitionistic/Deduction.lean
Logic/Propositional/Intuitionistic/Kripke/Completeness.lean
Logic/Propositional/Intuitionistic/Kripke/LEM.lean
Logic/Propositional/Translation.lean
Logic/Vorspiel/BinaryRelations.lean

Axiom T, D, B, 4, 5, .2, etc. is characterized by Geach Axiom. Every K extension closed by Geach axiom is Kripke complete.

feat(Modal): Strong completeness of Geach logics

---

Logic/Modal/Normal.lean
Logic/Modal/Normal/Axioms.lean
Logic/Modal/Normal/Deduction.lean
Logic/Modal/Normal/GL/Semantics.lean
Logic/Modal/Normal/GL/Soundness.lean
Logic/Modal/Normal/Geach.lean
Logic/Modal/Normal/HilbertStyle.lean
Logic/Modal/Normal/ModalCompanion.lean
Logic/Modal/Normal/Semantics.lean
Logic/Modal/Normal/Soundness.lean
Logic/Modal/Normal/Strength.lean
README.md

refactor(Modal): Refactor namings about modal axioms

---

README.md
md/src/README.md
md/src/SUMMARY.md
md/src/first_order/arithmetic_theories.md
md/src/first_order/arithmetics.md
md/src/first_order/goedel1.md

私はもうこのブランチに追記しない：コンフリクトする恐れはない．
`FirstIncompleteness`と`SelfReference`の証明について，証明方法としてどう違うのかよくわかっていないので追記しておいてほしい．

docs: Update Gödel's 1st Incompleteness

---

.gitattributes

chore: Remove JavaScript on language statistics

---

md/src/SUMMARY.md
md/src/references.md

知っている限りの様相論理に関する関連プロジェクトの記載を追加している．正直lean4-logicとしてやることかは怪しい．マージししだいZulipでも聞いてみる次第です．

docs: Related works of logic formalization

---

Logic/Modal/Standard/Formula.lean
Logic/Modal/Standard/Kripke/Filteration.lean
Logic/Modal/Standard/Kripke/Kripke.lean
Logic/Modal/Standard/Kripke/Semantics.lean

feat(Modal): Filteration Part.1

---

Logic/Modal/Standard/Deduction.lean
Logic/Modal/Standard/Geach.lean
Logic/Modal/Standard/Kripke/Filteration.lean
Logic/Modal/Standard/Kripke/GL.lean
Logic/Modal/Standard/Kripke/Geach.lean
Logic/Modal/Standard/Kripke/Semantics.lean
Logic/Modal/Standard/Kripke/Soundness.lean

`𝐊`の`𝗧`, `𝗗`, `𝗕`, `𝟰`に関する拡張は全て有限フレーム性を持つ．

feat(Modal): Filteration Part.2

---

Logic/Modal/Standard/Kripke/GL.lean
Logic/Modal/Standard/System.lean

`𝐆𝐋`ではネセシテーションの逆，すなわち`𝐆𝐋 ⊢! □p → 𝐆𝐋 ⊢! p`が成り立つ．

feat(Modal): Unnecessitation of `𝐆𝐋`

---

Logic/FirstOrder/Incompleteness/SelfReference.lean
Logic/Logic/Disjunctive.lean
Logic/Propositional/Superintuitionistic/Kripke/DP.lean

排中律を含む理論は完全なら選言特性を持つ（逆も然り）．したがって系として，第1不完全性定理が成り立つような`T`は完全ではないので選言特性を持たない．
Fixes #64

feat: Incompleteness and Disjunctive Property

---

Logic/Modal/Standard/Deduction.lean

feat(Modal): Add Solovay's Truth Provability Logic `𝐆𝐋𝐒`

---

Logic/FirstOrder/Incompleteness/DerivabilityCondition.lean
Logic/Modal/Standard/Provability/Basic.lean

Hilbert-Bernaysの導出可能性条件は別にあるため，Hilbert-Bernays-Löbに名前を修正

refactor(Incompleteness): Rename Derivability Condition

---

Logic/Modal/Standard/Kripke/GL/Completeness.lean
Logic/Modal/Standard/Kripke/Grz.lean
Logic/Modal/Standard/Kripke/Kripke.lean
Logic/Modal/Standard/System.lean

`𝗚𝗿𝘇` defines
- Transitive and Weak Converse Well-Founded
- Finite, Transitive and Antisymmetric

feat(Modal): Definability of `𝗚𝗿𝘇` 

---

Logic/Modal/Standard/Boxdot.lean
Logic/Modal/Standard/Kripke/GL/Boxdot.lean
Logic/Modal/Standard/Kripke/GL/GL.lean
Logic/Modal/Standard/Kripke/GL/Grz.lean

feat(Modal): Boxdot Property between `𝐆𝐫𝐳` and `𝐆𝐋`

---

Logic/FirstOrder/Basic/Calculus.lean
Logic/IntProp/ConsistentTableau.lean
Logic/IntProp/Kripke/Completeness.lean
Logic/IntProp/Kripke/LEM.lean
Logic/IntProp/Kripke/Semantics.lean
Logic/Logic/Calculus.lean
Logic/Logic/HilbertStyle/Basic.lean
Logic/Logic/HilbertStyle/Context.lean
Logic/Logic/System.lean
Logic/Modal/Complemental.lean
Logic/Modal/ConsistentTheory.lean
Logic/Modal/Kripke/Completeness.lean
Logic/Modal/Kripke/GL/MDP.lean
Logic/Modal/Kripke/GL/Tree.lean
Logic/Modal/Kripke/Geach.lean
Logic/Modal/Kripke/Semantics.lean
Logic/Modal/Maximal.lean
Logic/Modal/PLoN/Soundness.lean
Logic/Propositional/Classical/Basic/Calculus.lean

Revising Notations

---

Logic/Logic/HilbertStyle/Supplemental.lean
Logic/Modal/Axioms.lean
Logic/Modal/Boxdot/Basic.lean
Logic/Modal/Geach.lean
Logic/Modal/Hilbert.lean
Logic/Modal/Kripke/Completeness.lean
Logic/Modal/Kripke/Dot3.lean
Logic/Modal/Kripke/Geach.lean
Logic/Modal/Kripke/Semantics.lean
Logic/Modal/Kripke/Ver.lean
Logic/Modal/System.lean

- `𝐒𝟓𝐆𝐫𝐳 = 𝐓𝐫𝐢𝐯`
- Rename `𝗗(⊥)` to `𝗣`

refactor(Modal): some notations

---

.github/workflows/ci.yml

Summary側でimport-graphを生成すれば良いと思うためこれを削除．

ci: Remove import graph

---

Foundation/Logic/Disjunctive.lean
Foundation/Modal/Kripke/GL/MDP.lean
Foundation/Modal/Kripke/GL/Tree.lean
Foundation/Modal/LogicSymbol.lean
Foundation/Modal/MDP.lean
Foundation/Modal/ModalCompanion/Basic.lean
Foundation/Modal/System.lean

例えばKはMDPを持つためUnnecessitationはadmissibleになる．

feat(Modal): Unnecessitation of Modal Disjunctive Property

---

Foundation/IntProp/ConsistentTableau.lean
Foundation/IntProp/Deduction.lean
Foundation/IntProp/Kripke/Completeness.lean
Foundation/IntProp/Kripke/DP.lean
Foundation/IntProp/Kripke/LEM.lean
Foundation/IntProp/Kripke/Semantics.lean
Foundation/Logic/Disjunctive.lean
Foundation/Logic/HilbertStyle/Basic.lean
Foundation/Logic/HilbertStyle/Context.lean
Foundation/Logic/HilbertStyle/Lukasiewicz.lean
Foundation/Logic/HilbertStyle/Supplemental.lean
Foundation/Modal/Boxdot/GL_Grz.lean
Foundation/Modal/Complemental.lean
Foundation/Modal/Formula.lean
Foundation/Modal/Kripke/ComplexityLimited.lean
Foundation/Modal/Kripke/Dot3.lean
Foundation/Modal/Kripke/Filteration.lean
Foundation/Modal/Kripke/GL/Completeness.lean
Foundation/Modal/Kripke/GL/Definability.lean
Foundation/Modal/Kripke/GL/MDP.lean
Foundation/Modal/Kripke/GL/Tree.lean
Foundation/Modal/Kripke/Geach.lean
Foundation/Modal/Kripke/Grz/Completeness.lean
Foundation/Modal/Kripke/Grz/Definability.lean
Foundation/Modal/Kripke/S5.lean
Foundation/Modal/Kripke/Ver.lean
Foundation/Modal/Maximal.lean
Foundation/Modal/System.lean

メモ：`dhyp`と`imply₁'`は同じで，`dhyp`は`q`を明示的に与える必要があるが，これは煩雑なので非推奨にした（`(q := q)`としてください）．

Update 4.13 modal (2)

---

.github/workflows/update.yml

週に一度（日曜日の8時(UTC)）に自動的にLean自体の更新とMathlibなどの依存関係の更新を行う（成功すれば以下のようなPRが立つ / 失敗すればIssueが立つ（らしい））．この更新フローは手動でトリガーすることも出来る．
参考: https://github.com/SnO2WMaN/SmullyanTP/pull/1
close #104

Add auto update

---

.github/workflows/update.yml

ci: Change behavior when auto-update failed

---

Foundation/Modal/Hilbert/Geach.lean
Foundation/Modal/Hilbert/WellKnown.lean
Foundation/Modal/Kripke/Hilbert/KTc.lean
Foundation/Modal/Logic/Sublogic.lean
Foundation/Modal/Logic/Trivials.lean
Foundation/Modal/Logic/WellKnown.lean

Kripke semantical analysis only
close #206

Add Modal Logic KTc

---

Foundation.lean
Foundation/Modal/Logic/Basic.lean
Foundation/Modal/Logic/Sublogic/S4.lean
Foundation/Modal/ModalCompanion/Basic.lean
Foundation/Modal/ModalCompanion/Int.lean
Foundation/Modal/ModalCompanion/KC.lean
Foundation/Modal/ModalCompanion/LC.lean

Add Smallest Modal Companion for KC & LC

---

Foundation/Propositional/Kripke/Filteration.lean
Foundation/Propositional/Kripke/Hilbert/KC.lean
Foundation/Propositional/Kripke/Hilbert/LC.lean
Foundation/Propositional/Kripke/Preservation.lean
Foundation/Propositional/Kripke/Rooted.lean
Foundation/Vorspiel/RelItr.lean

Add filteration & point generation for Kripke semantics of propositional logics, and prove FFP of KC & LC.

feat(Int/Kripke): FFP of KC & LC

---

Foundation/Modal/ModalCompanion/Int.lean

feat(Modal): Embedding of Int and GL

---

Foundation/Modal/Boxdot/GLPoint3_GrzPoint3.lean
Foundation/Modal/Entailment/Basic.lean
Foundation/Modal/Hilbert/WellKnown.lean
Foundation/Modal/Kripke/Basic.lean
Foundation/Modal/Kripke/Hilbert/GLPoint3.lean
Foundation/Modal/Logic/WellKnown.lean
Foundation/Modal/ModalCompanion/LC.lean
Foundation/Vorspiel/Relation/Closure.lean

Add GL.3
- Soundness
- GL.3 is boxdot companion of Grz.3
- Embedding between LC and GL.3
Completeness is TODO.

feat(Modal): Add GL.3

---

Foundation/Modal/Kripke/Basic.lean
Foundation/Modal/Kripke/Hilbert/Triv.lean
Foundation/Modal/Logic/Sublogic/S5Grz.lean
Foundation/Modal/Logic/WellKnown.lean
Foundation/Modal/ModalCompanion/Cl.lean
Foundation/Propositional/Kripke/AxiomLEM.lean
Foundation/Propositional/Kripke/Hilbert/Cl.lean
Foundation/Propositional/Logic/WellKnown.lean
Foundation/Vorspiel/Relation/Supplemental.lean

feat(Modal): Triv is greatest modal companion of Cl

---

Foundation/Modal/Logic/Sublogic/GL.lean

feat(Modal): K4.3 and GL are sublogic of GL.3

---

Foundation.lean
Foundation/Incompleteness/DC/Basic.lean
Foundation/Modal/Kripke/ExtendRoot.lean
Foundation/Modal/Kripke/Rooted.lean
Foundation/Modal/Kripke/Tree.lean
Foundation/ProvabilityLogic/GL/Completeness.lean

https://iehality.github.io/notes-on-arithmetical-completeness/main.pdf 
Solovay文の構成は難しそうなのでPart.2で（まだ証明ちゃんと追えてないです）

feat(ProvabilityLogic): Arithmetical Completeness of GL Part.1

---

Foundation/Modal/Kripke/Hilbert/Ver.lean
Foundation/Modal/Logic/WellKnown.lean

feat(Modal/Kripke): FFP of Ver

---

Foundation/ProvabilityLogic/GL/Completeness.lean

fix(ProvabilityLogic): `SolovaySentences` only depend frame

---

Foundation/Modal/Axioms.lean
Foundation/Modal/Entailment/Basic.lean
Foundation/Modal/Entailment/KT.lean
Foundation/Modal/Hilbert/WellKnown.lean
Foundation/Modal/Kripke/AxiomMk.lean
Foundation/Modal/Kripke/Basic.lean
Foundation/Modal/Kripke/Completeness.lean
Foundation/Modal/Kripke/Hilbert/KTMk.lean
Foundation/Modal/Logic/WellKnown.lean
Foundation/Modal/LogicSymbol.lean
Foundation/Vorspiel/List/Chain.lean
Foundation/Vorspiel/List/Supplemental.lean

`KTMk` does not have FMP, completeness is not yet (later).

add(Modal/Kripke): Makinson's Logic `KTMk` without Finite Modal Property

---

Foundation/Modal/Kripke/AxiomM.lean
Foundation/Modal/Kripke/Logic/Grz/Completeness.lean

`Finite.exists_le_maximal`を使うためにMathlibの更新が必要なのでそれまで保留． #367

add(Modal): `Grz` is proper extension of `S4.1` 

---

Foundation/Modal/Axioms.lean
Foundation/Modal/Entailment/Basic.lean
Foundation/Modal/Entailment/GL.lean
Foundation/Modal/Entailment/Grz.lean
Foundation/Modal/Hilbert/WellKnown.lean
Foundation/Modal/Kripke/Basic.lean
Kite/Basic.lean
Kite/Modal.lean
Kite/Propositional.lean
Kite/modal.typ

add(Modal): Add axiom `Dum` and `Z`

---

.github/workflows/ci.yml
Foundation.lean
Foundation/FirstOrder/Arith/Induction.lean
Foundation/FirstOrder/Incompleteness/Delta1.lean
Foundation/ProvabilityLogic/Basic.lean
Kite/Arith.lean
Kite/arith.typ
lakefile.toml

Migrate Kite of Arithmetic Theories

---

Foundation.lean
Foundation/Modal/Axioms.lean
Foundation/Modal/Entailment/Basic.lean
Foundation/Modal/Entailment/GL.lean
Foundation/Modal/Hilbert/GL/Alternatives.lean
Foundation/Modal/Hilbert/WellKnown.lean
Foundation/Modal/Kripke/Logic/KHen.lean
Kite/modal.typ

refactor(Modal): Rename current axiom `H` to `Hen`

---

Foundation.lean
Foundation/Propositional/Entailment/Basic.lean
Foundation/Propositional/Hilbert/WellKnown.lean
Foundation/Propositional/Kripke/Logic/Cl.lean
Foundation/Propositional/Kripke/Logic/KC.lean
Foundation/Propositional/Kripke/Logic/KrieselPutnam.lean

refactor(Prop): Rename `KP` to `KrieselPutnam`

---

Foundation/Modal/Hilbert/KP.lean
Foundation/Modal/Hilbert/K_EMCN.lean
Foundation/Modal/Hilbert/S5Grz.lean
Foundation/Modal/Kripke/Logic/S5Grz.lean
Foundation/Modal/Maximal/Makinson.lean
Foundation/Modal/ModalCompanion/Cl.lean
Kite/Basic.lean
Kite/Modal.lean
Kite/modal.typ

fix(Kite): Fix Kite Generation

---

Foundation/Modal/Neighborhood/Basic.lean
Foundation/Modal/Neighborhood/Hilbert.lean
Foundation/Modal/Neighborhood/Logic/EMC.lean

add(Modal/Neighborhood): `𝐄𝐊 ⪱ 𝐄𝐌𝐂`

---

Foundation.lean
Foundation/FirstOrder/Incompleteness/Tarski.lean

実はあるのかもしれないが，とりあえず追加しておいた．リファクタリングは最終的な作業でやることにする．

add(FirstOrder): Tarski's Undefinability of Truth Theorem

---

Foundation.lean
Foundation/Modal/Kripke/Logic/KT4B.lean
Foundation/Modal/Logic/GLPlusBoxBot/Basic.lean
Zoo/modal.typ

add(Modal): `KT4B = S5`

---

Foundation/Modal/Kripke/Irreflexivize.lean
Foundation/Modal/Kripke/Logic/GLPoint3.lean
Foundation/Modal/Kripke/Logic/GrzPoint3.lean
Foundation/Modal/Kripke/Logic/Triv.lean
Foundation/Modal/Kripke/Logic/Ver.lean
Foundation/Modal/ModalCompanion/LC.lean
Foundation/Modal/Tableau.lean

add(Modal/Kripke): Kripke Completeness of `GL.3`
